### ISSUE TITLE
Enhancement: Add support for an Entitlements file

### ISSUE THREAD

**Issue by etter-tanium** [mitchellh/gon#3]
Add an optional `entitlements_file` string attribute to the `sign` config object. This will add the `--entitlements <filepath>` argument to the `codesign` command line.

https://github.com/etter-tanium/gon/blob/8ff56016325245ba1ddc327398bf86b35883863b/internal/config/config.go#L65
https://github.com/etter-tanium/gon/blob/8ff56016325245ba1ddc327398bf86b35883863b/sign/sign.go#L74

**Comment by mitchellh** [comment]
👍
