### ISSUE TITLE
No such environment variable for key: 'AC_PASSWORD' (-1005)

### ISSUE THREAD

**Issue by txoof** [mitchellh/gon#36]
I'm following the **excellent** configuration advice in the README to create my first notarized package. Thank goodness for `gon`! Apple does not make this process easy to figure out for first-time developers.

I'm stuck with the following errors shown below though with regards to notarizing.

I see that Issue #10 appears to address this, but I can't quite figure out how to get gon to fall back to asking for the `AC_PASSWORD`.

Honestly, I'm not sure what the `AC_PASSORD` is. I found [this article](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow) about setting an AC_PASSWORD in the keychain, but I'm a little nervous to do this; I'm not sure what I'm setting or how to undo it.

What am I missing?
```
  $ gon hello_world.hcl
==> ✏️  Signing files...
    Code signing successful
==> 📦  Creating Zip archive...
    Zip archive created with signed files
==> 📦  Creating dmg...
    Dmg created and signed
==> 🍎  Notarizing...
    Files will be notarized concurrently to optimize queue wait
    Path: hello_world.zip
    Path: hello_world.dmg
    [hello_world.dmg] Submitting file for notarization...
    [hello_world.dmg] Error notarizing
    [hello_world.zip] Submitting file for notarization...
    [hello_world.zip] Error notarizing

❗️ Error notarizing:

2 errors occurred:
	* 1 error occurred:
	* No such environment variable for key: 'AC_PASSWORD' (-1005)


	* 1 error occurred:
	* No such environment variable for key: 'AC_PASSWORD' (-1005)
```

For completeness here's my `.hcl` configuration.
```
source = ["./dist/hello_world"]
bundle_id = "com.txoof.helloworld"

apple_id {
  username = "my_emailaddress@foo.com"
  password = "@env:AC_PASSWORD"
}

sign {
  application_identity = "Developer ID Application: Aaron Ciuffo"
}

dmg {
  output_path = "hello_world.dmg"
  volume_name = "Hello"
}

zip {
  output_path = "hello_world.zip"
}
```

**Comment by txoof** [comment]
Solution:

Create an Application Specific Password for your Developer Account as suggested [here](https://scriptingosx.com/2019/09/notarize-a-command-line-tool/). 

Use the name created in the step suggested at the blog above (e.g. Developer-altool') in place of `'AC_PASSWORD'`.

**Comment by gedw99** [comment]
I also had to create an application specific password. It’s because I have 2DA in my apple account.

Everything works.
