### ISSUE TITLE
altool is deprecated? 

### ISSUE THREAD

**Issue by discentem** [mitchellh/gon#45]
Apparently `altool` is deprecated in favor of `notarytool`. See [this twitter thread](https://twitter.com/rosyna/status/1402065462641364997?s=20) and [these docs from Apple](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow).

Also `notarytool` has waiting/polling built-in. 😄 

I'm wondering if this means gon should switch to `notarytool`?

**Comment by mitchellh** [comment]
I probably have to take a pass at this to ensure everything is good for macOS 12. So, yes, you're probably right, I haven't read the new docs yet.

**Comment by discentem** [comment]
There's not necessarily a big rush. Just figured I'd flag the new tool. Apple often leaves tools around (even though they are deprecated) for _years_.

**Comment by andrewhsu** [comment]
I noticed an update to the timeline in WWDC2022 session [10109](https://developer.apple.com/videos/play/wwdc2022/10109/):
> notarization with all forms of altool will stop working in fall 2023

The session goes on to mention `notarytool` as a possible migration path, but encourages use of the notary API which is used as the backend for `notarytool`: https://developer.apple.com/documentation/notaryapi

**Comment by zwass** [comment]
@slayerjain yes it does. Would love to see someone do that work!
