### ISSUE TITLE
warning Calling Bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by gpkfr** [mitchellh/gon#54]
hello,

The Homebrew bottle need some update since ":unneeded" is deprecated.

Error messages on update with brew : 

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the mitchellh/gon tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/mitchellh/homebrew-gon/gon.rb:6

Thanks

**Comment by blacktop** [comment]
@mitchellh goreleaser fixed this issue recently so all you have to do is push out a new build using the latest version of goreleaser.

**Comment by trss** [comment]
I'm not into Go but I see a simplistic PR at https://github.com/mitchellh/homebrew-gon/pull/1. Will that do or is pushing out a new build using the latest version of goreleaser (whatever that is) needed?

Asking since if it's simpler, it has a greater chance of getting resolved.

**Comment by mitchellh** [comment]
Fixing this as part of #56
