### ISSUE TITLE
Unable to upload your app for notarization. (-1011)

### ISSUE THREAD

**Issue by Southclaws** [mitchellh/gon#60]
I hit this and couldn't find many mentions of this exact error code on the internet. Fortunately, I solved it so I'm just posting an issue to benefit others who may be searching for the same code.

From what I could tell, this happens because multi-device authentication is enabled for my account, so logins via my primary email+password pair typically require a secondary device (iPhone etc) to validate the authentication.

Obviously machine authentication cannot do this and it doesn't make sense for a CI pipeline anyway. The solution is actually mentioned in the docs but the error code is different (maybe outdated? Apple doesn't document this stuff...)

What you want is an application specific password in place of `AC_PASSWORD` which is done via this button:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1636971/168603908-8ee18cff-dd3b-41d8-94d8-de855beebdca.png">

On the page https://appleid.apple.com/account/manage

Hope that helps someone spend fewer hours figuring it out than I did!

**Comment by bdon** [comment]
For anyone else searching for solutions to this problem:

I had an inactive Developer account and had to accept all the updated agreements in App Store Connect before my notarizations seemed to upload.
