### ISSUE TITLE
Noob question, but can I use gon in linux, or just on a macos machine?

### ISSUE THREAD

**Issue by juandiegopalomino** [mitchellh/gon#63]

**Comment by jwatte** [comment]
Notarization uses proprietary binaries that Apple only distributes for their MacOS installs.
There is no way allowed by Apple to use those tools from a non-Mac machine.

**Comment by teras** [comment]
> @jwatte It would be nice to update the Readme.md file with a `Requirements` section. At the moment the MacOS + Xcode requirement is well hidden within the `Usage` section.

I second that. I had to dig inside this "noob' question since I had exactly the same.
