### ISSUE TITLE
bless: The 'openfolder' is not supported on Apple Silicon devices.

### ISSUE THREAD

**Issue by davidnewhall** [mitchellh/gon#64]
```
[david@ajn-im1]00:36:17|~/go/src/github.com/Notifiarr/notifiarr$ /Users/david/go/bin/gon gon.json
==> ✏️  Signing files...
    Code signing successful
==> 📦  Creating dmg...
    This will open Finder windows momentarily.
❗️ Error creating dmg:

error creating dmg:

Creating disk image...
created: /Users/david/go/src/github.com/Notifiarr/notifiarr/rw.notifiarr.dmg
Mounting disk image...
Unmounting disk image...
Mount directory: /Volumes/Notifiarr
Device name:     /dev/disk8
Copying custom files...
./notifiarr
Running Applescript: /usr/bin/osascript "/var/folders/ks/dgpqf8ld1qg5871wcc2fqw340000gn/T/createdmg.tmp.XXXXXXXXXX.Dzo8JSw2" "Notifiarr"
waited 1 seconds for .DS_STORE to be created.
Done running the applescript...
Fixing permissions...
Done fixing permissions.
Blessing started
bless: The 'openfolder' is not supported on Apple Silicon devices.
```

iMac M1 running macOS 12.4.
Installed gon by running: `go install github.com/mitchellh/gon/cmd/gon@latest`
Let me know if I can provide more info. This is the first time I've used this app.

**Comment by davidnewhall** [comment]
This app, with the same configs, works fine on my Intel MacBookPro.

**Comment by KMACEL** [comment]
When will reslease come out with this new fix?

**Comment by SubJunk** [comment]
[gon.zip](https://github.com/mitchellh/gon/files/10147808/gon.zip)
Here's a build of my fork of gon, which includes the fix for this problem

**Comment by bktexan87** [comment]
@SubJunk I just updated create-dmg via homebrew.  Is there an additional step I need to take after. I am still receiving the openfolder error

**Comment by SubJunk** [comment]
@bktexan87 I'm not part of this project, I just provided the file in my comment, which is the built version of my fork from https://github.com/UniversalMediaServer/gon

**Comment by KMACEL** [comment]
@SubJunk Thank you so much. Your binary is working

**Comment by hover-k8s-updater** [comment]
Any updates for this? I'm seeing the same error on M1 with MacOS Ventura 13.2.

**Comment by lionello** [comment]
Commenting the `dmg` section in the config file also avoids this error message (but you won't have a DMG)

**Comment by megavoid** [comment]
I submitted a Pull Request with a fix: https://github.com/mitchellh/gon/pull/73
