### ISSUE TITLE
Upgrade gon to notarytool

### ISSUE THREAD

**Issue by amlwwalker** [mitchellh/gon#68]
When notorizing using `gon`, the following message is displayed. Is there a plan to upgrade `gon`?
Thanks
```
	<array>
		<dict>
			<key>code</key>
			<integer>-1030</integer>
			<key>message</key>
			<string>altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.</string>
			<key>userInfo</key>
			<dict>
				<key>NSLocalizedDescription</key>
				<string>altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.</string>
			</dict>
		</dict>
	</array>
```

**Comment by mountaindude** [comment]
I've used gon for quite some time, awesome tool.

A while back I needed more control over the notarisation process in various GitHub actions, the solution was do sign and notarise the apps using more low-level commands.
More code than using gon but works well. 

If someone is interested, the action is available [here](https://github.com/ptarmiganlabs/butler-sheet-icons/blob/ddb9c9a8096a28d6295cad261bb6e1d9754c4a11/.github/workflows/ci.yml#L68).

**Comment by AnjirwalaAnuj** [comment]
Hi @mitchellh, can you please provide an estimated timeline for the upgrade to `notarytool`.

**Comment by bdon** [comment]
The [Apple docs now state](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool):

> Apple has deprecated altool for the purposes of notarization and [announced that it will stop working for notarization on 2023-11-01](https://developer.apple.com/news/?id=y5mjxqmn). However, altool is still a good way to perform other tasks, like submitting an app to the App Store.

@mnestor  + @mountaindude thanks for posting the workarounds!

**Comment by michaelquigley** [comment]
This is a showstopper for github.com/openziti/zrok.

**Comment by michaelquigley** [comment]
> This is a showstopper for github.com/openziti/zrok.

The issue with the `zrok` build was coming from `gon`, but the `notarytool` message is (currently) just a warning. Come to find out there were unacknowledged terms and conditions in the Apple account that were preventing signing. So, we're back in good shape for now.

Would definitely like to get in front of the `notarytool` thing before it becomes a showstopper, though.

**Comment by zwass** [comment]
@mitchellh this repo should really be "archived" if there is not going to be an upgrade to `notarytool`.

**Comment by mitchellh** [comment]
> @mitchellh this repo should really be "archived" if there is not going to be an upgrade to `notarytool`.

Agreed, the repository is now archived, updated the README with a notice.

Prior to archiving, I tried to merge the obviously correct PRs to keep the project in a working state for anyone who needs a transition period.
