### ISSUE TITLE
xcrun: error: unable to find utility "altool", not a developer tool or in PATH

### ISSUE THREAD

**Issue by tmc** [mitchellh/gon#69]
altool appears to have dropped out of the macos toolchain with `xcrun notarytool` replacing it.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

Relates to #68

**Comment by Valkyrie00** [comment]
Hi @mitchellh, have some news for us about this issue? Thanks 🙏

**Comment by mitchellh** [comment]
Fixed
